version: "3.8"
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=marketplace
      - POSTGRES_PASSWORD=awesomity
      - POSTGRES_DB=marketplacedb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5332:5432"

volumes:
  postgres: {}
