
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://marketplace:awesomity@postgres:5432/marketplacedb
    ports:
      - "3400:3400"  
      - "5555:5555"  # Port for Prisma Studio
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "
      yarn prisma:migrate &&
      yarn prisma:generate &&
      yarn start:dev
      "

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=marketplace
      - POSTGRES_PASSWORD=awesomity
      - POSTGRES_DB=marketplacedb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5332:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres: {}
